### ISSUE TITLE
Update pullMitreAttack because MITRE website changed

### ISSUE THREAD

**Issue by mrsheepsheep** [CyberCX-STA/PurpleOps#10]
https://github.com/CyberCX-STA/PurpleOps/blob/356802d8d4ad26ef15d3c50cd2219a104d63142b/seeder.py#L32

This is a dead link, and excel files URLs cannot be retrieved properly from the response.

https://attack.mitre.org/resources/working-with-attack/

New URL should be at https://attack.mitre.org/resources/attack-data-and-tools/.
Best solution should be to reference the components "repository" via a variable rather than obtaining the list from MITRE, which could break at any time. 

Fixing it also fixes #9

**Comment by mrsheepsheep** [comment]
Temporary fix by hardcoding xlsx file URLs :

```py
def pullMitreAttack (component):
    url = f"https://attack.mitre.org/docs/enterprise-attack-v14.1/enterprise-attack-v14.1-{component}.xlsx"
    req = requests.get(url)
    with open(f"{PWD}/external/mitre-{component}.xlsx", "wb") as mitreXLSX:
        mitreXLSX.write(req.content)

    wb = load_workbook(f"{PWD}/external/mitre-{component}.xlsx", read_only=True)
    ws = wb.active

    headers = [col.value for col in list(ws.rows)[0]]

    return [ws.rows, headers]
```

**Comment by joda32** [comment]
@mrsheepsheep Thanks for the catch. I've pushed the quick fix and will add a more permanent solution in the next big release.
