### ISSUE TITLE
docker build failed (Worker failed to boot.)

### ISSUE THREAD

**Issue by JohnRyk** [CyberCX-STA/PurpleOps#11]
Below is the docker log:

Waiting for Mongo...
[2024-01-25 08:18:24 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2024-01-25 08:18:24 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-01-25 08:18:24 +0000] [1] [INFO] Using worker: sync
[2024-01-25 08:18:24 +0000] [14] [INFO] Booting worker with pid: 14
[2024-01-25 08:18:25 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/purpleops.py", line 24, in <module>
    security = Security(app, user_datastore)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 1230, in __init__
    self.init_app(app, datastore, register_blueprint=register_blueprint)
  File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 1383, in init_app
    self.remember_token_serializer = _get_serializer(app, "remember")
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 718, in _get_serializer
    return URLSafeTimedSerializer(secret_key=secret_key, salt=salt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/itsdangerous/serializer.py", line 104, in __init__
    self.secret_keys: _t.List[bytes] = _make_keys_list(secret_key)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/itsdangerous/signer.py", line 64, in _make_keys_list
    return [want_bytes(s) for s in secret_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
[2024-01-25 08:18:25 +0000] [14] [INFO] Worker exiting (pid: 14)
[2024-01-25 08:18:25 +0000] [1] [INFO] Shutting down: Master
[2024-01-25 08:18:25 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by joda32** [comment]
Hi JohnRyk,
I'm unable to reproduce this, is it possible for you to attach the contents of your .env file and flask.cfg file. I just want to sanity check that. Also, the version of your OS and docker/compose version. Also, try deleting the docker image and have compose rebuild it.

**Comment by shrek3n** [comment]
Same issue :+1: 
`purpleops    | [2024-01-29 16:27:53 +0000] [1] [INFO] Starting gunicorn 20.1.0
purpleops    | [2024-01-29 16:27:53 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
purpleops    | [2024-01-29 16:27:53 +0000] [1] [INFO] Using worker: sync
purpleops    | [2024-01-29 16:27:53 +0000] [50] [INFO] Booting worker with pid: 50
mongodb      | {"t":{"$date":"2024-01-29T16:27:54.998+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:59446","uuid":{"uuid":{"$uuid":"18a17d7e-791e-4e9a-92c4-ffb89fe63b1e"}},"connectionId":5,"connectionCount":1}}
mongodb      | {"t":{"$date":"2024-01-29T16:27:55.004+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"172.18.0.3:59446","client":"conn5","doc":{"driver":{"name":"PyMongo","version":"4.4.1"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"6.3.0-kali1-amd64"},"platform":"CPython 3.11.3.final.0"}}}
purpleops    | [2024-01-29 16:27:54 +0000] [50] [ERROR] Exception in worker process
purpleops    | Traceback (most recent call last):
purpleops    |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
purpleops    |     worker.init_process()
purpleops    |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
purpleops    |     self.load_wsgi()
purpleops    |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
purpleops    |     self.wsgi = self.app.wsgi()
purpleops    |                 ^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
purpleops    |     self.callable = self.load()
purpleops    |                     ^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
purpleops    |     return self.load_wsgiapp()
purpleops    |            ^^^^^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
purpleops    |     return util.import_app(self.app_uri)
purpleops    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
purpleops    |     mod = importlib.import_module(module)
purpleops    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
purpleops    |     return _bootstrap._gcd_import(name[level:], package, level)
purpleops    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
purpleops    |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
purpleops    |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
purpleops    |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
purpleops    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
purpleops    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
purpleops    |   File "/usr/src/app/purpleops.py", line 24, in <module>
purpleops    |     security = Security(app, user_datastore)
purpleops    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 1230, in __init__
purpleops    |     self.init_app(app, datastore, register_blueprint=register_blueprint)
purpleops    |   File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 1383, in init_app
purpleops    |     self.remember_token_serializer = _get_serializer(app, "remember")
purpleops    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/flask_security/core.py", line 718, in _get_serializer
purpleops    |     return URLSafeTimedSerializer(secret_key=secret_key, salt=salt)
purpleops    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/itsdangerous/serializer.py", line 104, in __init__
purpleops    |     self.secret_keys: _t.List[bytes] = _make_keys_list(secret_key)
purpleops    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    |   File "/usr/local/lib/python3.11/site-packages/itsdangerous/signer.py", line 64, in _make_keys_list
purpleops    |     return [want_bytes(s) for s in secret_key]
purpleops    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
purpleops    | TypeError: 'NoneType' object is not iterable
purpleops    | [2024-01-29 16:27:55 +0000] [50] [INFO] Worker exiting (pid: 50)
mongodb      | {"t":{"$date":"2024-01-29T16:27:55.010+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:59456","uuid":{"uuid":{"$uuid":"95599a7c-8719-4c4a-af01-31d593d181dc"}},"connectionId":6,"connectionCount":2}}
mongodb      | {"t":{"$date":"2024-01-29T16:27:55.055+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn6","msg":"Connection ended","attr":{"remote":"172.18.0.3:59456","uuid":{"uuid":{"$uuid":"95599a7c-8719-4c4a-af01-31d593d181dc"}},"connectionId":6,"connectionCount":1}}
mongodb      | {"t":{"$date":"2024-01-29T16:27:55.507+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn5","msg":"Interrupted operation as its client disconnected","attr":{"opId":119}}
mongodb      | {"t":{"$date":"2024-01-29T16:27:55.544+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn5","msg":"Connection ended","attr":{"remote":"172.18.0.3:59446","uuid":{"uuid":{"$uuid":"18a17d7e-791e-4e9a-92c4-ffb89fe63b1e"}},"connectionId":5,"connectionCount":0}}
purpleops    | [2024-01-29 16:27:55 +0000] [1] [INFO] Shutting down: Master
purpleops    | [2024-01-29 16:27:55 +0000] [1] [INFO] Reason: Worker failed to boot.
purpleops exited with code 3
`

**Comment by joda32** [comment]
@shrek3n which OS and docker version are you using. Also, if possible try and delete both the mongo container as well as the purpleops image and try rebuild it.

**Comment by shrek3n** [comment]
> @shrek3n which OS and docker version are you using. Also, if possible try and delete both the mongo container as well as the purpleops image and try rebuild it.

debian/kali latest & Docker version 20.10.25+dfsg1, build b82b9f3

I deleted the images and containers and started fresh, but same result.

**Comment by cptwin** [comment]
@shrek3n @JohnRyk 
Can you provide the output of either
`docker-compose --version`
or
`docker compose version`

**Comment by shrek3n** [comment]
> @shrek3n @JohnRyk Can you provide the output of either `docker-compose --version` or `docker compose version`

docker-compose version 1.29.2, build unknown

**Comment by JohnRyk** [comment]
> @shrek3n @JohnRyk Can you provide the output of either `docker-compose --version` or `docker compose version`

Mine:
docker-compose version 1.29.2, build unknown

**Comment by cptwin** [comment]
Ok, I _think_ I might've at least narrowed it down.
Could either of you try deleting your containers and images for purpleops and mongodb (for this project).

Then edit compose.yml and change:
`image: mongo:latest`
to
`image: mongo:4.4.28`

give that a go and let me know if you are still getting the same error output.

**Comment by JohnRyk** [comment]
> Ok, I _think_ I might've at least narrowed it down. Could either of you try deleting your containers and images for purpleops and mongodb (for this project).
> 
> Then edit compose.yml and change: `image: mongo:latest` to `image: mongo:4.4.28`
> 
> give that a go and let me know if you are still getting the same error output.




CONTAINER ID   IMAGE                 COMMAND                  CREATED          STATUS          PORTS                                       NAMES
f689234bcda7   purpleops_purpleops   "/usr/src/app/entryp…"   19 seconds ago   Up 17 seconds   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   purpleops


This time the portal is up but the mongodb failed to boot 

```
Starting mongodb ... done
Starting purpleops ... done
Attaching to mongodb, purpleops
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.513+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.629+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.630+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"63415e11fdbd"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.630+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.28","gitVersion":"61c2baf63a060f7c12bd76e779044800ae18710b","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.630+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.630+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.631+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.631+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
mongodb      | {"t":{"$date":"2024-02-02T05:31:22.631+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=449M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.137+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:137324][1:0x7fd359541cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 14 through 15"}}
purpleops    | Waiting for Mongo...
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.339+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:339447][1:0x7fd359541cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 15 through 15"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.564+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:564073][1:0x7fd359541cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Main recovery loop: starting at 14/1920 to 15/256"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.714+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:714021][1:0x7fd359541cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 14 through 15"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.786+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:786792][1:0x7fd359541cc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 15 through 15"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.846+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:846354][1:0x7fd359541cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (0, 0)"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.846+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:846507][1:0x7fd359541cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (0, 0)"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.849+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:849259][1:0x7fd359541cc0], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 1, snapshot max: 1 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 994"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.918+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":1287}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.918+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.926+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.928+00:00"},"s":"W",  "c":"CONTROL",  "id":22120,   "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.945+00:00"},"s":"F",  "c":"CONTROL",  "id":20573,   "ctx":"initandlisten","msg":"Wrong mongod version","attr":{"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: BadValue: Invalid value for version, found 7.0, expected '4.4' or '4.2'. Contents of featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"7.0\" }. See https://docs.mongodb.com/master/release-notes/4.4-compatibility/#feature-compatibility.). If the current featureCompatibilityVersion is below 4.2, see the documentation on upgrading at https://docs.mongodb.com/master/release-notes/4.4/#upgrade-procedures."}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.945+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":10000}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"COMMAND",  "id":4784901, "ctx":"initandlisten","msg":"Shutting down the MirrorMaestro"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"initandlisten","msg":"Shutting down the WaitForMajorityService"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"initandlisten","msg":"Shutdown: going to close listening sockets"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"initandlisten","msg":"Shutting down the global connection pool"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"STORAGE",  "id":4784906, "ctx":"initandlisten","msg":"Shutting down the FlowControlTicketholder"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"initandlisten","msg":"Stopping further Flow Control ticket acquisitions."}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"STORAGE",  "id":4784908, "ctx":"initandlisten","msg":"Shutting down the PeriodicThreadToAbortExpiredTransactions"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"STORAGE",  "id":4784934, "ctx":"initandlisten","msg":"Shutting down the PeriodicThreadToDecreaseSnapshotHistoryCachePressure"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"REPL",     "id":4784909, "ctx":"initandlisten","msg":"Shutting down the ReplicationCoordinator"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"SHARDING", "id":4784910, "ctx":"initandlisten","msg":"Shutting down the ShardingInitializationMongoD"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"REPL",     "id":4784911, "ctx":"initandlisten","msg":"Enqueuing the ReplicationStateTransitionLock for shutdown"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"-",        "id":4784912, "ctx":"initandlisten","msg":"Killing all operations for shutdown"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"-",        "id":4695300, "ctx":"initandlisten","msg":"Interrupted all currently running operations","attr":{"opsKilled":3}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"COMMAND",  "id":4784913, "ctx":"initandlisten","msg":"Shutting down all open transactions"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"REPL",     "id":4784914, "ctx":"initandlisten","msg":"Acquiring the ReplicationStateTransitionLock for shutdown"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"INDEX",    "id":4784915, "ctx":"initandlisten","msg":"Shutting down the IndexBuildsCoordinator"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"REPL",     "id":4784916, "ctx":"initandlisten","msg":"Reacquiring the ReplicationStateTransitionLock for shutdown"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"REPL",     "id":4784917, "ctx":"initandlisten","msg":"Attempting to mark clean shutdown"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"initandlisten","msg":"Shutting down the ReplicaSetMonitor"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"initandlisten","msg":"Shutting down the MigrationUtilExecutor"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"STORAGE",  "id":4784929, "ctx":"initandlisten","msg":"Acquiring the global lock for shutdown"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"STORAGE",  "id":4784930, "ctx":"initandlisten","msg":"Shutting down the storage engine"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.947+00:00"},"s":"I",  "c":"STORAGE",  "id":22320,   "ctx":"initandlisten","msg":"Shutting down journal flusher thread"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.948+00:00"},"s":"I",  "c":"STORAGE",  "id":22321,   "ctx":"initandlisten","msg":"Finished shutting down journal flusher thread"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.948+00:00"},"s":"I",  "c":"STORAGE",  "id":20282,   "ctx":"initandlisten","msg":"Deregistering all the collections"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.948+00:00"},"s":"I",  "c":"STORAGE",  "id":22261,   "ctx":"initandlisten","msg":"Timestamp monitor shutting down"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.948+00:00"},"s":"I",  "c":"STORAGE",  "id":22317,   "ctx":"initandlisten","msg":"WiredTigerKVEngine shutting down"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.948+00:00"},"s":"I",  "c":"STORAGE",  "id":22318,   "ctx":"initandlisten","msg":"Shutting down session sweeper thread"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.948+00:00"},"s":"I",  "c":"STORAGE",  "id":22319,   "ctx":"initandlisten","msg":"Finished shutting down session sweeper thread"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.948+00:00"},"s":"I",  "c":"STORAGE",  "id":22322,   "ctx":"initandlisten","msg":"Shutting down checkpoint thread"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.949+00:00"},"s":"I",  "c":"STORAGE",  "id":22323,   "ctx":"initandlisten","msg":"Finished shutting down checkpoint thread"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.949+00:00"},"s":"I",  "c":"STORAGE",  "id":4795902, "ctx":"initandlisten","msg":"Closing WiredTiger","attr":{"closeConfig":"leak_memory=true,"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.950+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1706851883:950380][1:0x7fd359541cc0], close_ckpt: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 2, snapshot max: 2 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 994"}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.963+00:00"},"s":"I",  "c":"STORAGE",  "id":4795901, "ctx":"initandlisten","msg":"WiredTiger closed","attr":{"durationMillis":14}}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.963+00:00"},"s":"I",  "c":"STORAGE",  "id":22279,   "ctx":"initandlisten","msg":"shutdown: removing fs lock..."}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.963+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"initandlisten","msg":"Dropping the scope cache for shutdown"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.963+00:00"},"s":"I",  "c":"FTDC",     "id":4784926, "ctx":"initandlisten","msg":"Shutting down full-time data capture"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.963+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"initandlisten","msg":"Now exiting"}
mongodb      | {"t":{"$date":"2024-02-02T05:31:23.963+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"initandlisten","msg":"Shutting down","attr":{"exitCode":62}}
mongodb exited with code 62
```

**Comment by Zamanry** [comment]
I am using default env settings nd didn't run into this issue on Kali 2024.1 using Docker compose and commit 8c25c85f3738b77a67c1b13fa7f5edbac33c73e7.

**Comment by JohnRyk** [comment]
I tried to run the pull and run under the new version of kali (2024), and found it has no problem, so i will close this issue.
