### ISSUE TITLE
Custom reports not loaded

### ISSUE THREAD

**Issue by wsummerhill** [CyberCX-STA/PurpleOps#12]
After adding custom .docx reports to the `/custom/reports` folder, the reports are not loaded upon using the **Generate Report** button (shown below).

In my environment I'm using `sudo docker compose up` to start the PurpleOps instance which I don't think should change anything. I've also tried to stop docker, remove images/instances, and then restart docker to generate another report but custom reports are still not loaded.

![image](https://github.com/CyberCX-STA/PurpleOps/assets/35749735/48288397-b4c3-4b9e-9cb4-a1e6b659108c)
![image](https://github.com/CyberCX-STA/PurpleOps/assets/35749735/b41e1f89-8aa2-4050-9bb6-7b38f6489a1a)

**Comment by Piosec** [comment]
I've added the following line ```- ./custom:/usr/src/app/custom``` to compose.yml.  
![image](https://github.com/CyberCX-STA/PurpleOps/assets/26251854/d49c2673-f5e5-4b63-a51d-203190183759)

All the files in the custom folders are automatically shared with the container. 

Another alternative is ```docker cp```
