### ISSUE TITLE
Added Management Icon

### ISSUE THREAD

**Issue by shrek3n** [CyberCX-STA/PurpleOps#14]
The management icon is repeated multiple times in the drop down menu after creating additional targets and this is the same for all of those lists that an additional Management tab/icon is created which could be problematic or a feature :). 
![Screenshot_2024-03-06_08-00-32](https://github.com/CyberCX-STA/PurpleOps/assets/27941660/4681e19c-b2d5-42d2-abf4-e96a4e7c562b)

**Comment by turnernator1** [comment]
Hi @shrek3n, this was patched in latest commit (8d4503e)
