### ISSUE TITLE
Unauthorized 401 after installation

### ISSUE THREAD

**Issue by Cyb3rid10ts** [CyberCX-STA/PurpleOps#2]
after installation im getting 401 status error (below) automatically without prompting to authenticate. Any kind of help would be appreciated. Thank you.

"Unauthorized
The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."

**Comment by joda32** [comment]
Hi Cyb3rid10ts,

Quick questions,
1. which installation/running method did you follow?
2. can you provide some console out put 
3. the url you are connecting to
4. a screenshot of the browser before you try to login

**Comment by kfiducia** [comment]
If you are on a Mac there likely may already be something listening on the default port 5000 (airplay) - run a curl to check it without the docker containers running. Change the listening port and try again if so.

**Comment by Cyb3rid10ts** [comment]
thanks for the help, it was something to do with the mongo db port that i was using, change it to something else fixed it.
