### ISSUE TITLE
Uploading Attack Navigator Layers

### ISSUE THREAD

**Issue by kfiducia** [CyberCX-STA/PurpleOps#3]
Errors on keys missing, attribute errors. Not entirely sure all the data loaded. (looks like it worked but lots of errors thrown in terminal)

**Comment by Harrison-Mitchell** [comment]
Thanks for reporting - could you drop:

1. The raw `navigator.json`
2. A screenshot of the error
3. Any associated logs
4. How the `navigator.json` was generated (via PurpleOps - or the native applet)?

**Comment by Harrison-Mitchell** [comment]
Closed due to inactivity.
