### ISSUE TITLE
Error in Docker 

### ISSUE THREAD

**Issue by meetgyn** [CyberCX-STA/PurpleOps#4]
docker composer  up - error RUN apt-get update && apt-get install -y netcat git  

![image](https://github.com/CyberCX-STA/PurpleOps/assets/3695608/55f93229-2f3e-4ddf-a481-8506fd7bb013)

**Comment by Harrison-Mitchell** [comment]
Looks to be a local DNS issue `Temporary failure resolving 'deb.debian.org'` - often happens if you change VM networking without bouncing Docker. Closing due to out-of-scope issue.

**Comment by JohnRyk** [comment]
It  may cause by docker network issue:
1. Make sure your network can access the debian source `deb.debian.org`
2. restart docker service
```shell
sudo systemctl restart docker
```
