### ISSUE TITLE
Got error after restart docker

### ISSUE THREAD

**Issue by nobox910** [CyberCX-STA/PurpleOps#5]
Can't start app after run ```docker compose down``` and ```docker compose up```
![image](https://github.com/CyberCX-STA/PurpleOps/assets/58721688/cb9360d4-ef13-41b1-bf64-86b89b0d64f7)

**Comment by Harrison-Mitchell** [comment]
It would help if there was persistent storage so that the `secret_key` and `salt` didn't evaporate the moment you reboot the container. Fixed in 0f6c832 - thanks for reporting!
